import "../styles/globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Finanzas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Nav />
          <div className="p-4 sm:ml-32">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
